[0.7] Validate Sort SQL Column
bakaphp/baka pull request #119
Opened 2021-04-19 20:06 UTC by kaioken

- Avoid sending use a column not in the table

2021-04-19 20:25 UTC, rwhite27 approved these changes

2021-04-19 20:48 UTC, PaulMejiaFeliz requested changes

2021-04-19 20:48 UTC, PaulMejiaFeliz commented on src/Http/Converter/RequestUriToSql.php
> +        if (!is_null($sort) && Str::contains($sort, '|')) {
This will only allow to sort when there's a `|` on the string. Sorting without specifying the order wouldn't work, e.g. `?sort=name`

2021-04-20 15:09 UTC, FredPeal approved these changes

2021-04-26 14:42 UTC, PaulMejiaFeliz approved these changes

2021-04-26 14:47 UTC, merged