[0.7] Update Elastic Document
bakaphp/baka pull request #135
Opened 2021-06-08 20:23 UTC by kaioken

Allow elastic documents to work with a few more scenario`

```
<?php
class Creator extends Documents {
    public $id;
    public $name;
}

$creator = new Creator();
$creator->id = 2;
$creator->name = 'arfenids';
$creator->add();

$creator = new Creator([
    'id' => 1,
    'name' => 'max'
]);
$creator->add();

$creator->id = 2;
$creator->name = 'arfenids';
$creator->add();

$creator = new Creator([
    'id' => 1,
    'name' => 'max'
]);
$creator->add();
$creator->id = 2;
$creator->name = 'arfenids';
$creator->save();

```

2021-06-09 15:39 UTC, arfenis requested changes

2021-06-09 15:39 UTC, arfenis commented on src/Elasticsearch/Objects/Documents.php
> +        }
Move this to assign, and call assign in getdata

2021-06-11 14:24 UTC, FredPeal approved these changes

2021-06-11 14:31 UTC, arfenis approved these changes

2021-06-11 14:35 UTC, merged